POST http://localhost:8080/vehicle-api/plane
Content-Type: application/json

{
  "type": "Repcsi",
  "manufacturer": "Nagy",
  "passengerNumber": 120,
  "ownerID": 1
}

###

PUT http://localhost:8080/vehicle-api/plane
Content-Type: application/json

{
  "id": 2,
  "type": "Focus",
  "manufacturer": "Ford",
  "passengerNumber": "ASD-125"
}

###
GET http://localhost:8080/vehicle-api/plane
Accept: application/json

###

GET http://localhost:8080/vehicle-api/plane/o/1
Accept: application/json

###

DELETE http://localhost:8080/vehicle-api/plane/1
Accept: application/json

###

